package org.fiware.iam.tmforum.handlers;

import io.micronaut.core.annotation.Nullable;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpResponse;
import io.micronaut.http.HttpStatus;
import lombok.extern.slf4j.Slf4j;
import reactor.core.publisher.Mono;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

/**
 * Handler for events generated by the TMForum
 */
public interface TMForumEventHandler {

    /**
     * Return if the given handler implementation supports the given event type
     */
    boolean isEventTypeSupported(String eventType);

    /**
     * Handle the concrete event
     */
    Mono<HttpResponse<?>> handleEvent(String eventType, Map<String, Object> event);

    /**
     * Zip a list of HttpResponse Mono's. Return a success code in case all are fine, else a bad-gateway
     */
    default Mono<HttpResponse<?>> zipToResponse(List<Mono<HttpResponse<?>>> responses) {
        if (responses.isEmpty()) {
            return Mono.just(HttpResponse.noContent());
        }
        return Mono.zipDelayError(responses, objects -> Arrays.stream(objects)
                .filter(HttpResponse.class::isInstance)
                .map(HttpResponse.class::cast)
                .filter(response -> response.getStatus().getCode() < 200 || response.getStatus().getCode() > 299)
                .findAny()
                .map(response -> HttpResponse.status(HttpStatus.BAD_GATEWAY).body(response.body()))
                .orElse(HttpResponse.noContent()));
    }

}
