name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '21'
          java-package: jdk

      - id: ip
        run: |
          nmcli device show

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Run tests
        run: mvn clean verify jacoco:report coveralls:report -Dcoveralls.token=${{ secrets.COVERALLS_TOKEN }} -Dlocal.ip=${{ steps.ip.outputs.ipv4 }}

