name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '21'
          java-package: jdk

      - id: ip-test
        run: |

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Run tests
        run: |
          ips=$(hostname -I)
          ip_array=($ips)
          mvn clean verify jacoco:report coveralls:report -Dcoveralls.token=${{ secrets.COVERALLS_TOKEN }} -Dlocal.ip=${ip_array[0]}

